import type { NextPage } from "next";
import Head from "next/head";
import Nav from "../components/navbar";
const Index: NextPage = () => {
    return (
        <div>
            <Head>
                <title>HackTheBox SRMIST</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <div className="flex flex-col justify-center items-center h-screen">
                <img
                    src="/revealed_post.png"
                    alt="Unencrypted Post - HackTheBoxSRMIST"
                    className="my-0 md:w-2/5 w-4/5"
                />
                <a
                    href="https://discord.gg/vpWEV7bhms"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="bg-htb-green md:text-3xl text-2xl font-semibold md:px-8 px-6 py-2 rounded-full mt-16"
                >
                    JOIN US
                </a>
            </div>
        </div>
    );
};

export default Index;
